/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface OAlert {
    'alertId'?: string;
    'align': string;
    'line': boolean;
    'type': string;
  }
  interface OAlertAttributes extends StencilHTMLAttributes {
    'alertId'?: string;
    'align'?: string;
    'line'?: boolean;
    'type'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'OAlert': Components.OAlert;
  }

  interface StencilIntrinsicElements {
    'o-component-template': Components.OAlertAttributes;
  }


  interface HTMLOAlertElement extends Components.OAlert, HTMLStencilElement {}
  var HTMLOAlertElement: {
    prototype: HTMLOAlertElement;
    new (): HTMLOAlertElement;
  };

  interface HTMLElementTagNameMap {
    'o-component-template': HTMLOAlertElement
  }

  interface ElementTagNameMap {
    'o-component-template': HTMLOAlertElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
