/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface OInput {
      'block': boolean;
      'disabled': boolean;
      'fill': 'dashed' | 'outline' | 'solid';
      'href': string;
      'rounded': boolean;
      'size': string;
      'target': string;
      'type': string;
    }
  }

  interface HTMLOInputElement extends StencilComponents.OInput, HTMLStencilElement {}

  var HTMLOInputElement: {
    prototype: HTMLOInputElement;
    new (): HTMLOInputElement;
  };
  interface HTMLElementTagNameMap {
    'o-input': HTMLOInputElement;
  }
  interface ElementTagNameMap {
    'o-input': HTMLOInputElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'o-input': JSXElements.OInputAttributes;
    }
  }
  namespace JSXElements {
    export interface OInputAttributes extends HTMLAttributes {
      'block'?: boolean;
      'disabled'?: boolean;
      'fill'?: 'dashed' | 'outline' | 'solid';
      'href'?: string;
      'rounded'?: boolean;
      'size'?: string;
      'target'?: string;
      'type'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;